<?php $this->headTitle($this->title); ?>

<h1 class="page-header"><?= $this->title ?></h1>

<?php
$this->mainMenu($this->main_menu ?: []);
?>

<ul class="list-group">
    <?php if (isset($this->main_menu)): ?>
        <?php foreach ($this->main_menu as $menu) : ?>
            <li class="list-group-item"><a href="<?= $menu["link"] ?>">
                    <?= $menu["title"] ?>
                </a></li>
        <?php endforeach; ?>
    <?php endif; ?>
</ul>