<?php $this->headTitle('Stats barcode'); ?>

<h2>Товары</h2>

<div class="row">
    <div class="col-md-offset-1 col-md-4">
        <h3>Статистика сканирования баркодов</h3>
        <table class="table table-bordered table-hover">
            <tr>
                <td>FNSKU (barcode)</td>
                <td>IP Address</td>
                <td>Scan Time (UTC)</td>
            </tr>
            <?php foreach ($this->data as $item) : ?>
            <tr>
                <td><?php echo $item['FNSKU'] ?></td>
                <td><?php echo $item['ip'] ?></td>
                <td><?php echo date('c', $item['scanTime']) ?></td>
            </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>