<?php $this->headTitle($this->title); ?>

<h1 class="page-header"><?= $this->title ?></h1>

<h2><a href="<?php echo $this->url("select-parcel") ?>">Parcel <?= $this->parcelNumber ?></a></h2>

<style>
    .top-buffer {
        margin-top: 20px;
    }
</style>

<?php
$this->mainMenu($this->main_menu ?: []);
?>

<?php /* Search form */ ?>

<script>
    function startBarcodeScanner() {
        window.location.href = 'bwstw://startscanner?field=barcode_text';
    }
</script>

<div class="row">
    <div class="col-md-offset-3 col-md-4">
        <h3>Barcode scanning</h3>
        <form enctype="multipart/form-data"
              action="<?php echo $this->url('search-barcode', ["parcel_number" => $this->parcelNumber]) ?>"
              method="GET">
            <div class="form-group">
                <label for="pwd"> Item barcode:</label>
                <input id="barcode_text" class="form-control" name="barcode" type="text" autofocus/>
                <input class="btn btn-info" type="submit" value="View item"/>
            </div>
        </form>
        <button type="button" onclick="javascript:startBarcodeScanner();" class="btn btn-success btn-lg">
            Start Scanning
        </button>
    </div>
</div>

<div class="row">
    <div class="col-md-offset-1 col-md-12">
        <?php if (isset($this->barcode) && !empty($this->barcode)): ?>
            <?php if (isset($this->notify)) : ?>
                <p><?php echo $this->notify ?></p>
            <?php else: ?>
                <div class="row">
                    <div class="col-md-4">
                        <h3>Barcode: <?php echo $this->barcode ?></h3>
                        <h3>Part number: <?php echo $this->barcodeInfo['part_number'] ?></h3>
                        <ul class="list-group">
                            <?php if (!empty($this->barcodeInfo['quantity'])) : ?>
                                <?php foreach ($this->barcodeInfo['quantity'] as $boxName => $boxQuantity): ?>
                                    <li class="list-group-item"><?= $boxName ?>: <?= $boxQuantity ?></li>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <img class="img-rounded" src="<?php echo $this->barcodeInfo['image_link'] ?>"
                             style="width: 100%;">
                    </div>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    </div>
</div>
